### ISSUE TITLE
Author Information

### ISSUE THREAD

**Issue by bluegenes** [bluegenes/2021-paper-sourmash-distance#3]
This issue is to collect `yaml`-formatted author information to be added to the manuscript.

@luizirber @dkoslicki @olgabot please add/update your info when you have time.

using luiz for a format example:
```
  - github: luizirber
    name: Luiz Irber
    initials: LI
    orcid: 0000-0003-4371-9659
    twitter: luizirber
    email: lcirberjr@ucdavis.edu
    affiliations:
      - Graduate Group in Computer Science, UC Davis
      - Department of Population Health and Reproduction, UC Davis
    funders:
      - Grant XXXXXXXX
```

Note that this manuscript is in flux, and may be split into two, with separately-determined authorship. But all of you will be on at least one, if not both :).

**Comment by dkoslicki** [comment]
```
  - github: dkoslicki
    name: David Koslicki
    initials: DK
    orcid: 0000-0002-0640-954X
    twitter: DavidKoslicki
    email: dmk333@psu.edu
    affiliations:
      - Computer Science and Engineering, Penn State University
      - Department of Biology, Penn State University
      - Huck Institutes of the Life Sciences, Penn State University
    funders:
      - NSF Grant #1664803
```

**Comment by taylorreiter** [comment]
```
  - github: taylorreiter
    name: Taylor Reiter
    initials: TER
    orcid: 0000-0002-7388-421X
    twitter: ReiterTaylor
    email: tereiter@ucdavis.edu
    affiliations:
      - Department of Population Health and Reproduction, UC Davis
    funders:
      - Grant XXXXXXXX
 ```

**Comment by olgabot** [comment]
```
  -
    github: olgabot
    name: Olga Borisovna Botvinnik
    initials: OBB
    orcid: 0000-0003-4412-7970
    twitter: olgabot
    email: olga.botvinnik@czbiohub.org
    affiliations:
      - Data Sciences Platform, Chan Zuckerberg Biohub
```
